export const ResearchProposal = () => (
  <>
    <p>
      Based on the literature review mentioned earlier, I proposed an idea for
      new research. Below you can find the ‘pitch’ I wrote to base my proposal
      and research on.
    </p>
    <p>
      The research will explore the financial impacts of implementing machine
      learning-driven recommendation systems in the fashion e-commerce industry,
      with a focus on customer profiling and personalisation. It will aim to
      fill a gap in the existing research, which often focuses on marketing
      metrics without considering the direct financial implications. The study
      will quantify the costs and benefits of recommendation engines, helping
      businesses understand whether the upfront and ongoing investments lead to
      increased profitability.
    </p>
    <p>
      This research is important because businesses, especially emerging ones
      with limited resources, need clearer insights into whether adopting such
      technologies is financially viable. Given the fierce competition and
      narrow profit margins in e-commerce, understanding the true costs of
      implementing these systems is crucial for informed decision-making.
    </p>
    <p>
      To conduct the research, the study will collaborate with nine UK-based
      fashion e-commerce companies of varying sizes. All businesses will use
      Amazon Personalize as their recommendation engine, ensuring consistency
      across the study. The research will track expenses (setup and maintenance)
      and revenue generated by the recommendation systems, comparing costs and
      benefits across businesses of different sizes. Quantitative data such as
      the percentage of recommended products purchased will be used to evaluate
      the system’s financial performance. Additionally, customer sentiment will
      be gauged through interviews.
    </p>
    <p>
      The study will span approximately three years, with the first year focused
      on business recruitment and framework development, followed by two years
      of data collection and analysis. The ultimate goal is to create a
      financial impact assessment framework that businesses can use to evaluate
      their own recommendation systems. This research could guide future
      cost-effective personalisation strategies in e-commerce.
    </p>
  </>
);
